In [1]:
import pandas as pd

df_pair_qa = pd.read_csv('../data/medical-diff-vqa-1.0.1/mimic_pair_questions.csv')
df_pair_qa.shape

(700703, 7)

In [2]:
df_pair_qa.head()

,study_id,subject_id,ref_id,question_type,question,answer,split
0,55088298,18936629,54989200,abnormality,what abnormalities are seen in the soft tissues?,atelectasis,train
1,55088298,18936629,54989200,presence,is there edema?,no,train
2,55088298,18936629,54989200,location,is the atelectasis located on the left side or...,left side,train
3,55088298,18936629,54989200,level,what level is the pneumothorax?,minimal,train
4,55088298,18936629,54989200,difference,what has changed compared to the reference image?,the main image has an additional finding of pn...,train

In [3]:
df_pair_qa_train = df_pair_qa[df_pair_qa['split'] == 'train']
df_pair_qa_val = df_pair_qa[df_pair_qa['split'] == 'val']
df_pair_qa_test = df_pair_qa[df_pair_qa['split'] == 'test']
df_pair_qa_train.shape, df_pair_qa_val.shape, df_pair_qa_test.shape

((560563, 7), (70070, 7), (70070, 7))

In [4]:
df_pair_qa_train = df_pair_qa_train.drop(columns=['split'])
df_pair_qa_val = df_pair_qa_val.drop(columns=['split'])
df_pair_qa_test = df_pair_qa_test.drop(columns=['split'])
df_pair_qa_train.shape, df_pair_qa_val.shape, df_pair_qa_test.shape

((560563, 6), (70070, 6), (70070, 6))

In [5]:
df_all = pd.read_csv('../data/medical-diff-vqa-1.0.1/mimic_all.csv')
df_all.shape

(227827, 21)

In [6]:
df_all.head()

,subject_id,study_id,Atelectasis,Cardiomegaly,Consolidation,Edema,Enlarged Cardiomediastinum,Fracture,Lung Lesion,Lung Opacity,...,Pleural Effusion,Pleural Other,Pneumonia,Pneumothorax,Support Devices,dicom_id,view,split,study_date,study_order
0,10000032,50414267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,02aa804e-bde0afdd-112c0b34-7bc16630-4e384014,postero-anterior,train,21800506,1.0
1,10000032,53189527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab,postero-anterior,train,21800626,2.0
2,10000032,53911762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714,antero-posterior,train,21800723,3.0
3,10000032,56699142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,ea030e7a-2e3b1346-bc518786-7a8fd698-f673b44c,antero-posterior,train,21800805,4.0
4,10000764,57375967,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-1.0,NaN,NaN,096052b7-d256dc40-453a102b-fa7d01c6-1b22c6b4,antero-posterior,train,21321015,1.0

In [7]:
df_all['split'].unique()

array(['train', 'validate', 'test'], dtype=object)

In [8]:
df_all_train = df_all[df_all['split'] == 'train']
df_all_val = df_all[df_all['split'] == 'validate']
df_all_test = df_all[df_all['split'] == 'test']
df_all_train.shape, df_all_val.shape, df_all_test.shape

((222750, 21), (1808, 21), (3269, 21))

In [9]:
df_all_train = df_all_train.drop(columns=['split'])
df_all_val = df_all_val.drop(columns=['split'])
df_all_test = df_all_test.drop(columns=['split'])
df_all_train.shape, df_all_val.shape, df_all_test.shape

((222750, 20), (1808, 20), (3269, 20))

In [10]:
df_pair_qa_train.to_csv('E:\\MIMIC-CXR-JPG-224x224\\mimic_pair_questions_train.csv', index=False)
df_pair_qa_val.to_csv('E:\\MIMIC-CXR-JPG-224x224\\mimic_pair_questions_val.csv', index=False)
df_pair_qa_test.to_csv('E:\\MIMIC-CXR-JPG-224x224\\mimic_pair_questions_test.csv', index=False)
df_all_train.to_csv('E:\\MIMIC-CXR-JPG-224x224\\mimic_all_train.csv', index=False)
df_all_val.to_csv('E:\\MIMIC-CXR-JPG-224x224\\mimic_all_val.csv', index=False)
df_all_test.to_csv('E:\\MIMIC-CXR-JPG-224x224\\mimic_all_test.csv', index=False)